Update install

diff --git a/scripts/install b/scripts/install
--- a/scripts/install
+++ b/scripts/install
@@ -100,13 +100,13 @@ ynh_setup_source "$final_path"
 #=================================================
 
 # Check SHA1
-if ! sha1sum -c ../conf/htpasswd.checksum &> /dev/null
- then
-      echo "htpasswd Integrity Error"
-      exit
-  else
-      echo "htpasswd Integrity Success"
-fi
+#if ! sha1sum -c ../conf/htpasswd.checksum &> /dev/null
+# then
+#      echo "htpasswd Integrity Error"
+#      exit
+#  else
+#      echo "htpasswd Integrity Success"
+#fi
 
 #=================================================
 # MODIFY A CONFIG FILE
